- name: install and run nginx # name is not mandatory but this is good practice
  hosts: mongodb
  become: yes # this will give root access
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: start nginx
      ansible.builtin.services:
        name: nginx
        state: started